spring.application.name=railway
spring.datasource.url=jdbc:mysql://root:bugmVkDIUBAmhPpmLspdyRvvRqbKpsCA@autorack.proxy.rlwy.net:27861/railway
spring.datasource.username=root
spring.datasource.password=bugmVkDIUBAmhPpmLspdyRvvRqbKpsCA
